### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'formatters'

### ISSUE THREAD

**Issue by artofhuman** [coagulant/copydog#1]
After exec command copydog --fullsync --config=/redmine/trello_config.yaml show this error
ConfigParser.NoSectionError: No section: 'formatters'

**Comment by deedos** [comment]
same happend with me

**Comment by KarstenFritz** [comment]
It was a bug in the example config. I have fixed it.

**Comment by coagulant** [comment]
Fixed in #2
